### ISSUE TITLE
Could you create an Appimage of this for Linux?

### ISSUE THREAD

**Issue by older-pack** [LongSoft/FD44Editor#5]
UEFITool and FD44Editor are great tools.
Could you create an [Appimage](https://appimage.org) versions for Linux?
(I'm not able to compile my own Linux app)
Thank you

(Same request on [UEFITool](https://github.com/LongSoft/UEFITool/issues/124) too.)

**Comment by NikolajSchlej** [comment]
This project is not supported or maintained.
