### ISSUE TITLE
The program does not save the file

### ISSUE THREAD

**Issue by Rifju** [LongSoft/FD44Editor#6]
Help, when trying to save a save window appears, I enter the name, clicks ok, and nothing happens

**Comment by NikolajSchlej** [comment]
Try selecting the same file you have opened. If still doesn't work, please attach the file you are trying to edit.

**Comment by Rifju** [comment]
ok, I was able to save the file, but I encountered another problem. The first time the bios updated successfully, but when I try to install the same bios with other data I get the error "bios build date is too old". Are you able to add the option to change the bios version to the application?
