### ISSUE TITLE
Is there a specific tool for Intel BIOS?

### ISSUE THREAD

**Issue by rtek1000** [LongSoft/FD44Editor#8]
Hello,

Regarding the procedure for file BIOS with extension .BIO (in this case an Intel DG965MQ motherboard), UEFItool opens the file normally, extracts and everything, but the extracted file (.ROM) has the same size as the .BIO file. Which is larger than the EEPROM memory.

In other words, the EEPROM is a 25VF080 that has 1MB but the extracted file is 1.199.556 bytes and should have 1.048.576 bytes to fit in memory. Do I need to do anything else?

BIOS Files:
https://rebyte.me/en/intel/124551/file-545043/
http://www.opendrivers.com/modeldriver/intel_dg965mq-driver-download.html

**Comment by NikolajSchlej** [comment]
There's no easy way to convert .BIO file into something that can be flashed into SPI chip as-is.
